#### general settings
name: ir-sde
use_tb_logger: true
model: denoising
distortion: derain
gpu_ids: [0,1,2,3]
batch_size: &batch_size 8
GT_size: &GT_size 256

sde:
  max_sigma: 30 #也许30/255对于图像补全来说有点大？
  T: 100 #400
  schedule: cosine
  eps: 0.005

degradation:
  mask_root: /home/chengzy/mural-completion/dataset/muralV3/Masks/
  
#### datasets
datasets:
  train:
    name: Train_Dataset
    mode: GT
    dataroot_GT: /home/chengzy/mural-completion/dataset/muralV3/Images/
    dataroot_LQ: /home/chengzy/mural-completion/dataset/muralV3/Degraded/
    dataroot_Mask: /home/chengzy/mural-completion/dataset/muralV3/Masks/
    use_shuffle: true
    n_workers: 8
    use_flip: true
    use_rot: true
    color: RGB
    origin_mask: True
    origin_size: 768
    GT_size: *GT_size
    batch_size: *batch_size
    segment: True


#### network structures
network_G:
  which_model_G: ConditionalUNet
  setting:
    in_nc: 3
    out_nc: 3
    nf: 64
    depth: 4

tensordec: tucker
TDNet:
  ranks: [128, 128, 16]
  algo: NN
  mid_channel: 128
  max_iter: 3000


#### path
path:
  strict_load: true
  resume_state: ~
  pretrain_model: /home/chengzy/mural-completion/models/0903.pth

#### training settings: learning rate scheme, loss
train:
  optimizer: Adam
  lr_G: !!float 5e-5 #1e-4
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99
  niter: 12000 #80000
  warmup_iter: -1  # no warm up
  lr_steps: [3000, 6000, 9000]
  lr_gamma: 0.5
  eta_min: !!float 1e-7

  # criterion
  is_weighted: False
  loss_type: l1
  weight: 1.0

  manual_seed: 0

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
